site_name: EEStUdy Place
site_description: The learning site you are viewing is created by EESU Academic Department. It is a place for students to learn and share knowledge.
repo_name: ZJU-EESUAD/EEStUdy-Place
repo_url: https://github.com/ZJU-EESUAD/EEStUdy-Place
copyright: Copyright &copy; EESUAD
use_directory_urls: false
nav:
  - Home: index.md
  - About:
    - 关于网站: About/关于网站.md
    - 关于我们: About/关于我们.md
    - 贡献指南: About/Contributing.md
    - 课程模板: About/Template.md
    - 我要反馈: About/Issue.md
    - 致谢: About/Authors.md
  - All In One:
    - All_In_One/index.md
    - 培养方案: All_In_One/培养方案.md
    - CC98 全科目就读感想: All_In_One/CC98.md
    - 个人网站汇总帖: All_In_One/Notes.md
    - 课程资料整理: All_In_One/Resources.md
    - 友链: All_In_One/Links.md
    
  - 通识必修课:
    - 通识必修课/index.md
    - 微积分: 
      - 微积分(甲)I、II: 通识必修课/微积分/微积分（甲）.md
      - 微积分(甲)II: 通识必修课/微积分/微积分(甲)II.md
    - 大学物理: 通识必修课/大学物理/大学物理.md
    - 毛泽东思想概论: 通识必修课/毛泽东思想概论/毛泽东思想概论.md
  - 专业基础课:
    - 专业基础课/index.md 
    - 常微分方程: 专业基础课/常微分方程/常微分方程.md
    - 工程训练: 专业基础课/工程训练/工程训练.md
    - 工程图学: 专业基础课/工程图学/工程图学.md
    - 复变函数与积分变换: 专业基础课/复变函数与积分变换/复变函数与积分变换.md
    - 概率论与数理统计: 专业基础课/概率论与数理统计/概率论与数理统计.md
  - 专业必修课:
    - 专业必修课/index.md
    - 公共方向课:
      - 专业必修课/公共方向课/人工智能与物联网/人工智能与物联网.md
      - 专业必修课/公共方向课/信号分析与处理/信号分析与处理.md
      - 专业必修课/公共方向课/工程电磁场与波/工程电磁场与波.md
      - 微机原理与应用:
        - 专业必修课/公共方向课/微机原理与应用/微处理器原理及应用.md
        - 专业必修课/公共方向课/微机原理与应用/微机原理与应用.md
        - 专业必修课/公共方向课/微机原理与应用/微机原理与接口技术.md
      - 专业必修课/公共方向课/控制理论（乙）/控制理论（乙）.md
      - 专业必修课/公共方向课/数字电路分析与设计/数字电路分析与设计.md
      - 电力电子技术:
        - 专业必修课/公共方向课/电力电子技术/EE3202M 电力电子技术.md
        - 专业必修课/公共方向课/电力电子技术/EE3501M 电力电子技术Ⅰ.md
      - 专业必修课/公共方向课/电网络分析/电网络分析.md
      - 专业必修课/公共方向课/电路与电子技术I、II/电路与电子技术I、II.md
    - 电气工程及其自动化: 
      - 专业必修课/电气工程及其自动化/电力系统暂态分析/电力系统暂态分析.md
      - 专业必修课/电气工程及其自动化/电力系统稳态分析/电力系统稳态分析.md
      - 专业必修课/电气工程及其自动化/电机与拖动/电机与拖动.md
      - 专业必修课/电气工程及其自动化/电机学/电机学.md
      - 专业必修课/电气工程及其自动化/电机控制/电机控制.md
      - 专业必修课/电气工程及其自动化/电机系统建模与分析/电机系统建模与分析.md
      - 专业必修课/电气工程及其自动化/计算方法/计算方法.md
    - 电子信息工程: 
      - 专业必修课/电子信息工程/信息论与编码/信息论与编码.md
      - 专业必修课/电子信息工程/半导体物理/半导体物理.md
      - 专业必修课/电子信息工程/电力电子器件及其集成电路/电力电子器件及其集成电路.md
      - 专业必修课/电子信息工程/离散数学/离散数学.md
      - 专业必修课/电子信息工程/计算机网络与通信/计算机网络与通信.md
      - 专业必修课/电子信息工程/通信原理/通信原理.md
    - 自动化: 
      - 专业必修课/自动化/自动化导论/自动化导论.md
      - 专业必修课/自动化/自动控制理论/自动控制理论.md
      - 专业必修课/自动化/现代控制理论/现代控制理论.md
      - 专业必修课/自动化/嵌入式系统/嵌入式系统.md
      - 专业必修课/自动化/人工智能进阶与实践/人工智能进阶与实践.md
    
  - 专业选修课: 
    - 专业选修课/index.md
    - 公共:
      - 专业选修课/公共/信号与系统/信号与系统.md
      - 专业选修课/公共/数值计算方法/数值计算方法.md
      - 专业选修课/公共/数据结构与算法分析/数据结构与算法分析.md
      - 专业选修课/公共/计算机网络原理/计算机网络原理.md
      - 专业选修课/公共/运筹学/运筹学.md
      - 专业选修课/公共/面向对象的编程技术-C++/面向对象的编程技术-C++.md
      - 专业选修课/公共/面向对象的编程技术-JAVA/面向对象的编程技术-JAVA.md
    - 电气工程及其自动化:
      - 高电压技术: 专业选修课/电气工程及其自动化/高电压技术/高电压技术.md
      - 现代电机CAD技术: 专业选修课/电气工程及其自动化/现代电机CAD技术/现代电机CAD技术.md
      - 发电厂电气系统: 专业选修课/电气工程及其自动化/发电厂电气系统/发电厂电气系统.md
      - 电气装备计算机控制技术: 专业选修课/电气工程及其自动化/电气装备计算机控制技术/电气装备计算机控制技术.md
    - 电子信息工程: 
      - 电子测量与智能仪器: 专业选修课/电子信息工程/电子测量与智能仪器/电子测量与智能仪器.md
      - 计算机软件技术基础: 专业选修课/电子信息工程/计算机软件技术基础/计算机软件技术基础.md
      - 科学创新方法论及实践: 专业选修课/电子信息工程/科学创新方法论及实践/科学创新方法论及实践.md
      - DSP原理与应用: 专业选修课/电子信息工程/DSP原理与应用/DSP原理与应用.md
      - 电力电子技术II: 专业选修课/电子信息工程/电力电子技术II/电力电子技术II.md
      - 电子器件与装备热管理: 专业选修课/电子信息工程/电子器件与装备热管理/电子器件与装备热管理.md
    - 自动化:
      - 专业选修课/自动化/先进控制基础/先进控制基础.md
      - 专业选修课/自动化/控制与决策系统仿真/控制与决策系统仿真.md
      - 专业选修课/自动化/数字图像处理与机器视觉/数字图像处理与机器视觉.md
      - 专业选修课/自动化/智能制造与企业自动化/智能制造与企业自动化.md
      - 专业选修课/自动化/智能控制技术/智能控制技术.md
      - 专业选修课/自动化/最优控制与强化学习/最优控制与强化学习.md
      - 专业选修课/自动化/电气控制技术/电气控制技术.md

  - 实践课程:
    - 实践课程/index.md
    - 电子信息工程:
      - 实践课程/电子信息工程/index.md
    - 电气工程及其自动化:
      - 实践课程/电气工程及其自动化/index.md
    - 自动化:
      - 实践课程/自动化/index.md
      - 实践课程/自动化/专业认知/专业认知.md
      - 实践课程/自动化/人工智能与大数据综合实践/人工智能与大数据综合实践.md
      - 实践课程/自动化/智能电气及自动化综合实践/智能电气及自动化综合实践.md
      - 实践课程/自动化/机器人与智能系统综合实践/机器人与智能系统综合实践.md
      - 实践课程/自动化/自动化实训1/自动化实训1.md
      - 实践课程/自动化/自动化竞赛实训/自动化竞赛实训.md
      - 实践课程/自动化/自动化综合创新实践/自动化综合创新实践.md
      - 实践课程/自动化/企业深度实习/企业深度实习.md
      - 实践课程/自动化/实验技能训练/实验技能训练.md
      - 实践课程/自动化/嵌入式系统设计与实践/嵌入式系统设计与实践.md
      - 实践课程/自动化/嵌入式系统高级实验/嵌入式系统高级实验.md
      - 实践课程/自动化/测控系统综合实践/测控系统综合实践.md
      - 实践课程/自动化/电子工程训练/电子工程训练.md
      - 实践课程/自动化/电工电子实习/电工电子实习.md
      - 实践课程/自动化/科研训练/科研训练.md

    - 学科竞赛: 实践课程/竞赛.md
  - EEFuture:
    - 逐梦手册: EEFuture/逐梦手册.md
    - 学习手册: EEFuture/学习手册.md
    - 实验室介绍: EEFuture/实验室介绍.md
    
  - 资源站: http://file.eestudy-place.com/files/files/



theme:
  name: material
  language: zh
  custom_dir: material/overrides
  features:
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes  # 在导航中显示索引页, 即index.md不占用新的页面
    - navigation.tracking
    - content.code.annotate
    - toc.follow
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share

  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue #, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: indigo # [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo #, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent:  blue # [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - assets/javascripts/katex.js


extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - assets/stylesheets/extra.css
  - assets/stylesheets/card.css # 课程笔记卡片
  - assets/stylesheets/flink.css # 友链卡片
  - assets/stylesheets/fold_toc.css
  - assets/stylesheets/toc_extra.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tasklist
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - mdx_truly_sane_lists # 支持多级列表

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZJU-EESUAD

plugins:
  - search
  # - changelog

hooks:
  # toc页面，改编自https://github.com/TonyCrane/note/tree/master/hooks，效果还不稳定
  - hooks/toc_manager.py